---
title: Justin Cuizon

timezone: UTC

permalink: /:categories/:title/

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

name: Justin Cuizon

markdown: kramdown

highlighter: rouge

exclude:
- node_modules
- gulpfile.js
- package.json

baseurl: ''
